# frozen_string_literal: true

require_relative "../test_helper"
require_relative "../support/rake_task_application"

module TasksTests
  class FixtureCleanupTest < Test::Unit::TestCase
    include RakeTaskApplication

    def test_clean_deletes_only_marked_fixtures_and_manifest
      marked = File.join(@fixtures, "marked.yml")
      edited_marked = File.join(@fixtures, "edited_marked.yml")
      unmarked = File.join(@fixtures, "unmarked.yml")
      lookalike = File.join(@fixtures, "lookalike.yml")
      gitkeep = File.join(@fixtures, ".gitkeep")
      File.write(marked, MARKER + "fixture: true\n")
      File.write(edited_marked, MARKER + "human_edit: true\n")
      File.write(unmarked, "fixture: true\n")
      File.write(lookalike, "# Generated by fixture_builder. Do not edit. extra\n")
      File.write(gitkeep, "")
      FileUtils.mkdir_p("tmp")
      File.write("tmp/fixture_builder.yml", "manifest\n")

      invoke :clean

      assert_path_not_exist marked
      assert_path_not_exist edited_marked
      assert_path_not_exist "tmp/fixture_builder.yml"
      assert_equal "fixture: true\n", File.read(unmarked)
      assert_path_exist lookalike
      assert_path_exist gitkeep
    end

    def test_clean_uses_configured_paths_without_running_factory
      configured = File.join(@directory, "configured_fixtures")
      manifest = File.join(@directory, "tmp/custom_manifest.yml")
      FileUtils.mkdir_p([configured, File.dirname(manifest)])
      write_configuration(<<~RUBY)
        FixtureBuilder.configure do |fbuilder|
          fbuilder.fixture_directory = #{configured.dump}
          fbuilder.fixture_builder_file = #{manifest.dump}
          fbuilder.factory { raise "factory ran during clean" }
        end
      RUBY
      configured_marked = File.join(configured, "marked.yml")
      configured_unmarked = File.join(configured, "unmarked.yml")
      default_marked = File.join(@fixtures, "marked.yml")
      File.write(configured_marked, MARKER + "fixture: true\n")
      File.write(configured_unmarked, "fixture: true\n")
      File.write(default_marked, MARKER + "fixture: true\n")
      File.write(manifest, "manifest\n")

      invoke :clean

      assert_path_not_exist configured_marked
      assert_path_not_exist default_marked
      assert_path_not_exist manifest
      assert_equal "fixture: true\n", File.read(configured_unmarked)
    end
  end
end
