# frozen_string_literal: true

require_relative "../test_helper"
require "rake"
require "tmpdir"

module TasksTests
  class FixtureCleanupTest < Test::Unit::TestCase
    MARKER = "# Generated by fixture_builder. Do not edit.\n"

    def setup
      @original_application = Rake.application
      @original_fixtures_path = ActiveRecord::Tasks::DatabaseTasks.fixtures_path
      @original_directory = Dir.pwd
      @directory = Dir.mktmpdir("fixture-builder-clean-task")
      @fixtures = File.join(@directory, "generated_fixtures")
      FileUtils.mkdir_p(@fixtures)
      Dir.chdir(@directory)
      ActiveRecord::Tasks::DatabaseTasks.fixtures_path = Pathname.new(@fixtures)
      Rake.application = Rake::Application.new
      load Rails.root.join("lib/tasks/fixture_builder.rake")
    end

    def teardown
      Rake.application = @original_application
      ActiveRecord::Tasks::DatabaseTasks.fixtures_path = @original_fixtures_path
      Dir.chdir(@original_directory)
      FileUtils.remove_entry(@directory) if File.exist?(@directory)
    end

    def test_clean_deletes_only_marked_fixtures_and_manifest
      marked = File.join(@fixtures, "marked.yml")
      edited_marked = File.join(@fixtures, "edited_marked.yml")
      unmarked = File.join(@fixtures, "unmarked.yml")
      lookalike = File.join(@fixtures, "lookalike.yml")
      gitkeep = File.join(@fixtures, ".gitkeep")
      File.write(marked, MARKER + "fixture: true\n")
      File.write(edited_marked, MARKER + "human_edit: true\n")
      File.write(unmarked, "fixture: true\n")
      File.write(lookalike, "# Generated by fixture_builder. Do not edit. extra\n")
      File.write(gitkeep, "")
      FileUtils.mkdir_p("tmp")
      File.write("tmp/fixture_builder.yml", "manifest\n")

      Rake::Task["spec:fixture_builder:clean"].invoke

      assert_path_not_exist marked
      assert_path_not_exist edited_marked
      assert_path_not_exist "tmp/fixture_builder.yml"
      assert_equal "fixture: true\n", File.read(unmarked)
      assert_path_exist lookalike
      assert_path_exist gitkeep
    end
  end
end
