# frozen_string_literal: true

require_relative "../test_helper"
require "tmpdir"

module ConfigurationTests
  class CleanTest < Test::Unit::TestCase
    MARKER = "# Generated by fixture_builder. Do not edit.\n"

    def setup
      @directory = Dir.mktmpdir("fixture-builder-clean")
      @rails_fixtures = File.join(@directory, "rails_fixtures")
      @configured_fixtures = File.join(@directory, "configured_fixtures")
      FileUtils.mkdir_p([@rails_fixtures, @configured_fixtures])
      @previous_fixtures_path = ActiveRecord::Tasks::DatabaseTasks.fixtures_path
      ActiveRecord::Tasks::DatabaseTasks.fixtures_path = @rails_fixtures
      @configuration = FixtureBuilder::Configuration.new.tap do |config|
        config.fixture_directory = @configured_fixtures
        config.fixture_builder_file = File.join(@directory, "manifest.yml")
      end
    end

    def teardown
      ActiveRecord::Tasks::DatabaseTasks.fixtures_path = @previous_fixtures_path
      FileUtils.remove_entry(@directory)
    end

    def test_removes_manifest_and_marked_fixtures_from_both_directories
      File.write(@configuration.fixture_builder_file, "version: 1\n")
      [@rails_fixtures, @configured_fixtures].each do |directory|
        File.write(File.join(directory, "generated.yml"), MARKER + "generated: true\n")
        File.write(File.join(directory, "hand_written.yml"), "hand_written: true\n")
      end

      @configuration.clean

      assert_path_not_exist @configuration.fixture_builder_file
      [@rails_fixtures, @configured_fixtures].each do |directory|
        assert_equal ["hand_written.yml"], Dir.children(directory)
      end
    end
  end
end
