# frozen_string_literal: true

require_relative "../test_helper"
require "tmpdir"

module ConfigurationTests
  class GeneratedFileMarkerTest < Test::Unit::TestCase
    MARKER = "# Generated by fixture_builder. Do not edit.\n"

    with_model :MarkerRecord do
      table { |table| table.string :name }
    end

    def setup
      @directory = Dir.mktmpdir("fixture-builder-marker-migration")
      @fixtures = File.join(@directory, "fixtures")
      @manifest = File.join(@directory, "fixture_builder.yml")
      @source = File.join(@directory, "source.rb")
      FileUtils.mkdir_p(@fixtures)
      File.write(@source, "source\n")
    end

    def teardown
      FileUtils.remove_entry(@directory) if File.exist?(@directory)
    end

    def test_migrates_compatible_v1_without_overwrite_warning
      write_unmarked_fixture
      orphan = fixture_path("stale_records")
      orphan_contents = "hand_authored: true\n"
      File.binwrite(orphan, orphan_contents)
      write_manifest
      builds = 0

      _output, warning = capture_output do
        configuration.factory do
          builds += 1
          MarkerRecord.create!(name: "Migrated")
        end
      end

      assert_equal 1, builds
      assert_empty warning
      assert_equal MARKER, File.open(fixture_path, &:readline)
      assert_equal orphan_contents, File.binread(orphan)
    end

    def test_persists_adoption_after_success
      write_unmarked_fixture
      write_manifest
      builds = 0
      config = configuration
      config.factory do
        builds += 1
        MarkerRecord.create!(name: "Migrated")
      end

      manifest = YAML.safe_load_file(@manifest)
      assert_equal 1, manifest.fetch("version")
      assert_equal true, manifest.fetch("generated_file_marker")
      assert_equal Digest::SHA256.file(fixture_path).hexdigest,
        manifest.fetch("fixtures").fetch("#{MarkerRecord.table_name}.yml")

      config.factory { builds += 1 }
      assert_equal 1, builds
    end

    def test_warns_on_unmarked_collision_after_adoption
      config = configuration
      config.factory { MarkerRecord.create!(name: "First") }
      File.write(fixture_path, "unmarked: true\n")

      _output, warning = capture_output do
        config.factory { MarkerRecord.create!(name: "Second") }
      end

      assert_include warning, "replacing an unmarked fixture"
      assert_equal "Second", YAML.safe_load_file(fixture_path).dig("second", "name")
    end

    data(
      "missing manifest" => nil,
      "flat manifest" => {"source.rb" => "digest"},
      "unsupported version" => {"version" => 2, "sources" => {}, "fixtures" => {}},
      "extra key" => {"version" => 1, "sources" => {}, "fixtures" => {}, "extra" => true},
      "false marker" => {"version" => 1, "sources" => {}, "fixtures" => {}, "generated_file_marker" => false},
      "null marker" => {"version" => 1, "sources" => {}, "fixtures" => {}, "generated_file_marker" => nil},
      "string marker" => {"version" => 1, "sources" => {}, "fixtures" => {}, "generated_file_marker" => "true"}
    )
    def test_does_not_suppress_for_unrecognized_manifests(manifest)
      write_unmarked_fixture
      manifest ? File.write(@manifest, manifest.to_yaml) : FileUtils.rm_f(@manifest)

      _output, warning = capture_output do
        configuration.factory { MarkerRecord.create!(name: "Current") }
      end

      assert_include warning, "replacing an unmarked fixture"
      assert_equal true, YAML.safe_load_file(@manifest).fetch("generated_file_marker")
    end

    def test_does_not_adopt_when_after_build_raises
      write_unmarked_fixture
      write_manifest
      config = configuration
      config.after_build = proc { raise "after build failure" }

      assert_raise(RuntimeError) do
        config.factory { MarkerRecord.create!(name: "Failed") }
      end
      assert_path_not_exist @manifest

      File.write(fixture_path, "still_unmarked: true\n")
      retry_config = configuration
      _output, warning = capture_output do
        retry_config.factory { MarkerRecord.create!(name: "Retried") }
      end
      assert_include warning, "replacing an unmarked fixture"
    end

    def test_does_not_adopt_when_output_write_fails
      write_unmarked_fixture
      write_manifest
      config = configuration
      output_path = fixture_path
      fixture_directory = @fixtures

      assert_raise(Errno::EACCES) do
        config.factory do
          FileUtils.rm_f(output_path)
          File.chmod(0o500, fixture_directory)
          MarkerRecord.create!(name: "Failed")
        end
      end

      assert_path_not_exist @manifest
    ensure
      File.chmod(0o700, @fixtures) if File.exist?(@fixtures)
    end

    def test_rechecks_adoption_under_generation_lock
      write_unmarked_fixture
      write_manifest
      config = configuration
      config.define_singleton_method(:rebuild_fixtures_preflight?) do
        adopted = YAML.safe_load_file(fixture_builder_file)
        adopted["generated_file_marker"] = true
        adopted["fixtures"]["#{MarkerRecord.table_name}.yml"] = "stale"
        File.write(fixture_builder_file, adopted.to_yaml)
        true
      end

      _output, warning = capture_output do
        config.factory { MarkerRecord.create!(name: "Locked") }
      end

      assert_include warning, "replacing an unmarked fixture"
    end

    private

    def configuration
      FixtureBuilder::Configuration.new.tap do |config|
        config.fixture_directory = @fixtures
        config.fixture_builder_file = @manifest
        config.files_to_check = [@source]
        config.skip_tables = ActiveRecord::Base.connection.tables - [MarkerRecord.table_name]
        config.write_empty_files = false
      end
    end

    def fixture_path(table_name = MarkerRecord.table_name)
      File.join(@fixtures, "#{table_name}.yml")
    end

    def write_unmarked_fixture
      File.write(fixture_path, {"old" => {"name" => "Old"}}.to_yaml)
    end

    def write_manifest
      fixtures = Dir.glob(File.join(@fixtures, "*.yml")).to_h do |path|
        [File.basename(path), Digest::SHA256.file(path).hexdigest]
      end
      File.write(@manifest, {
        "version" => 1,
        "sources" => {@source => Digest::SHA256.file(@source).hexdigest},
        "fixtures" => fixtures
      }.to_yaml)
    end
  end
end
