# frozen_string_literal: true

require_relative "../test_helper"
require "tmpdir"

# standard:disable Rails/ApplicationRecord
class OwnershipRecord < ActiveRecord::Base
end
# standard:enable Rails/ApplicationRecord

module BuilderTests
  class GeneratedFixtureOwnershipTest < Test::Unit::TestCase
    MARKER = "# Generated by fixture_builder. Do not edit.\n"

    def setup
      @directory = Dir.mktmpdir("fixture-builder-ownership")
      # with_table captures this adapter when the suite loads, so reset the
      # in-memory database without replacing its connection pool.
      connection = ActiveRecord::Base.connection
      connection.tables.each { |table| connection.drop_table(table) }
      connection.create_table(:ownership_records) { |table| table.string :name }
      OwnershipRecord.reset_column_information
    end

    def teardown
      FileUtils.remove_entry(@directory) if File.exist?(@directory)
    end

    def test_marks_populated_and_empty_output
      generate { OwnershipRecord.create!(name: "Gandalf") }

      populated = fixture_path("ownership_records")
      empty = fixture_path("empty_records")
      assert_equal MARKER, File.open(populated, &:readline)
      assert_equal MARKER, File.open(empty, &:readline)
      assert_equal "Gandalf", YAML.safe_load_file(populated).dig("gandalf", "name")
      assert_equal({}, YAML.safe_load_file(empty))

      OwnershipRecord.delete_all
      ActiveRecord::FixtureSet.create_fixtures(@directory, "ownership_records")
      assert_equal "Gandalf", OwnershipRecord.find_by!(name: "Gandalf").name
    end

    def test_removes_marked_fixture_after_table_is_dropped
      ActiveRecord::Base.connection.create_table(:dropped_records) { |table| table.string :name }
      generate(tables: %w[ownership_records empty_records dropped_records])
      stale = fixture_path("dropped_records")
      assert_path_exist stale
      ActiveRecord::Base.connection.drop_table(:dropped_records)

      generate { OwnershipRecord.create!(name: "Current") }

      assert_path_not_exist stale
      assert_path_exist fixture_path("ownership_records")
    end

    def test_preserves_unmarked_orphans
      orphan = fixture_path("unknown_records")
      File.binwrite(orphan, "unknown: true\n")

      generate { OwnershipRecord.create!(name: "Current") }

      assert_equal "unknown: true\n", File.binread(orphan)
    end

    def test_requires_exact_first_line_marker
      paths = {
        "extra" => "# Generated by fixture_builder. Do not edit. extra\n",
        "missing" => "# Generated by fixture_builder\n",
        "later" => "fixture: true\n#{MARKER}"
      }.transform_values.with_index do |contents, index|
        path = fixture_path("lookalike_#{index}")
        File.write(path, contents)
        [path, contents]
      end

      generate { OwnershipRecord.create!(name: "Current") }

      paths.each_value { |path, contents| assert_equal contents, File.read(path) }
    end

    def test_removes_edited_marked_orphans
      stale = fixture_path("edited_records")
      File.write(stale, MARKER + "human_edit: true\n")

      generate { OwnershipRecord.create!(name: "Current") }

      assert_path_not_exist stale
    end

    def test_warns_before_overwriting_unmarked_current_output
      path = fixture_path("ownership_records")
      File.write(path, "old: true\n")

      _output, warning = capture_output { generate { OwnershipRecord.create!(name: "Current") } }

      assert_include warning, path
      assert_include warning, "replacing an unmarked fixture"
      assert_equal 1, warning.scan(path).length
      assert_equal MARKER, File.open(path, &:readline)
    end

    def test_overwrites_marked_output_without_warning
      path = fixture_path("ownership_records")
      File.write(path, MARKER + "edited: true\n")

      _output, warning = capture_output { generate { OwnershipRecord.create!(name: "Current") } }

      assert_empty warning
      assert_equal "Current", YAML.safe_load_file(path).dig("current", "name")
    end

    def test_preserves_unmarked_omitted_empty_output
      marked = fixture_path("empty_records")
      unmarked = fixture_path("ownership_records")
      File.write(marked, MARKER + "{}\n")
      File.write(unmarked, "hand_authored: true\n")

      _output, warning = capture_output { generate(write_empty_files: false) }

      assert_path_not_exist marked
      assert_equal "hand_authored: true\n", File.read(unmarked)
      assert_empty warning
    end

    def test_removes_marked_output_for_newly_skipped_table
      marked = fixture_path("skipped_records")
      unmarked = fixture_path("other_skipped_records")
      File.write(marked, MARKER + "{}\n")
      File.write(unmarked, "hand_authored: true\n")

      generate { OwnershipRecord.create!(name: "Current") }

      assert_path_not_exist marked
      assert_path_exist unmarked
    end

    private

    def generate(
      write_empty_files: true,
      legacy_marker_migration: false,
      tables: %w[ownership_records empty_records],
      &block
    )
      ActiveRecord::Base.connection.create_table(:empty_records) unless ActiveRecord::Base.connection.table_exists?(:empty_records)
      configuration = FixtureBuilder::Configuration.new
      configuration.fixture_directory = @directory
      configuration.write_empty_files = write_empty_files
      configuration.skip_tables = ActiveRecord::Base.connection.tables - tables
      FixtureBuilder::Builder.new(
        configuration,
        FixtureBuilder::Namer.new(configuration),
        block || proc {},
        legacy_marker_migration: legacy_marker_migration
      ).generate!
    end

    def fixture_path(table_name)
      File.join(@directory, "#{table_name}.yml")
    end
  end
end
