# frozen_string_literal: true

require "rake"
require "tmpdir"

# Runs the spec:fixture_builder rake tasks against a throwaway application root
# with its own file-backed test database. Including this module registers setup
# and teardown hooks that restore Rake, Rails.root, the fixtures path, the
# Active Record connection, the shared FixtureBuilder configuration, and the
# required configuration files.
module RakeTaskApplication
  MARKER = "# Generated by fixture_builder. Do not edit.\n"

  def self.included(base)
    base.setup :set_up_rake_task_application, before: :prepend
    base.teardown :tear_down_rake_task_application, after: :append
  end

  def set_up_rake_task_application
    @original_application = Rake.application
    @original_fixtures_path = ActiveRecord::Tasks::DatabaseTasks.fixtures_path
    @original_directory = Dir.pwd
    @original_configurations = ActiveRecord::Base.configurations
    @original_db_config = current_db_config
    @original_fixture_builder_configuration = FixtureBuilder.instance_variable_get(:@configuration)
    @original_root = Rails.method(:root)
    @directory = File.realpath(Dir.mktmpdir("fixture-builder-rake-task"))
    @fixtures = File.join(@directory, "generated_fixtures")
    FileUtils.mkdir_p(@fixtures)
    Dir.chdir(@directory)
    ActiveRecord::Tasks::DatabaseTasks.fixtures_path = Pathname.new(@fixtures)
    ActiveRecord::Base.configurations = {
      "test" => {"adapter" => "sqlite3", "database" => File.join(@directory, "test.sqlite3")}
    }
    FixtureBuilder.instance_variable_set(:@configuration, nil)
    application_root = Pathname.new(@directory)
    replace_rails_root { application_root }
    Rake.application = Rake::Application.new
    load File.expand_path("../../lib/tasks/fixture_builder.rake", __dir__)
    Rake::Task.define_task(:environment)
  end

  def tear_down_rake_task_application
    $LOADED_FEATURES.reject! { |feature| feature.start_with?(@directory) }
    replace_rails_root(&@original_root)
    FixtureBuilder.instance_variable_set(:@configuration, @original_fixture_builder_configuration)
    ActiveRecord::Base.configurations = @original_configurations
    ActiveRecord::Base.establish_connection(@original_db_config) if @original_db_config
    Rake.application = @original_application
    ActiveRecord::Tasks::DatabaseTasks.fixtures_path = @original_fixtures_path
    Dir.chdir(@original_directory)
    FileUtils.remove_entry(@directory) if File.exist?(@directory)
  end

  def invoke(*task_names) = task_names.each { |name| Rake::Task["spec:fixture_builder:#{name}"].invoke }

  def write_configuration(source)
    path = File.join(@directory, "spec/support/fixture_builder.rb")
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, source)
  end

  private

  def replace_rails_root(&)
    Rails.singleton_class.send(:remove_method, :root)
    Rails.define_singleton_method(:root, &)
  end

  def current_db_config
    ActiveRecord::Base.connection_db_config
  rescue ActiveRecord::ConnectionNotEstablished
    nil
  end
end
