# frozen_string_literal: true

module FixtureBuilder
  class FixtureFile
    MARKER = "# Generated by fixture_builder. Do not edit.\n"

    attr_reader :path

    def initialize(path)
      @path = path.to_s
    end

    def generated?
      File.open(path, &:readline) == MARKER
    rescue EOFError, Errno::ENOENT
      false
    end

    def write(yaml, suppress_unmarked_warning: false)
      warn_before_unmarked_overwrite unless suppress_unmarked_warning || !File.exist?(path) || generated?
      File.write(path, MARKER + yaml)
    end

    def delete_if_generated
      FileUtils.rm_f(path) if generated?
    end

    private

    # standard:disable Rails/Output
    def warn_before_unmarked_overwrite
      warn "FixtureBuilder is replacing an unmarked fixture at #{path}"
    end
    # standard:enable Rails/Output
  end
end
